org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false


# Minecraft Information
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.112
neo_version_range=[26.1.2.21-beta,)
loader_version_range=[4,)


# Mod information
mod_version=1.2.3
mod_group_id=nadiendev.ae2nometeorcraters
mod_id=ae2nometeorcraters
mod_name=AE2NoMeteorCraters
mod_named=AE2 No Meteor Craters
mod_description=Forces all AE2 meteorites to generate with crater type NONE, preventing any terrain destruction while keeping the meteorite itself intact.
mod_license=MIT
mod_author=NadienDev
issue_tracker=https://github.com/SrNadien/AE2-No-Meteor-Crates/issues
tag_platform=NeoForge


# Mod dependencies
ae2_version=26.1.12-beta
ae2_version_range=[26.1.10-beta,)
guideme_version=26.1.14-beta
