org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Partchment 
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false


# Minecraft Information
minecraft_version=1.21.1
neo_version=21.1.215
loader_version_range=[4,)


# Mod information
mod_version=1.1.0
mod_group_id=nadiendev.ae2nometeorcrates
mod_id=ae2nometeorcrates
mod_name=AE2NoeteorCrates
mod_named=AE2 No Meteor Crates
mod_description=Forces all AE2 meteorites to generate with crater type NONE, preventing any terrain destruction while keeping the meteorite itself intact.
mod_license=MIT
mod_author=NadienDev
issue_tracker= https://github.com/SrNadien/AE2-No-Meteor-Crates/issues.
tag_platform=NeoForge


# Mod dependencies
ae2_version=19.2.17
guideme_version=21.1.15
jei_version=19.27.0.340
